experiment:
    project: "eval/llada_math"
    deepspeed_file: "dp_zero3"

model:
    pretrained_model: [
        "/path/to/llada-8b-instruct",
        "/path/to/your/checkpoint",
    ]
    model_type: "llada"

training:
    reward_funcs: ["math"]
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 2026

evaluation:
    eval_dataset: ["MATH500", "gsm8k_test", "AMC"]
    data_type: "math"
    temperature: 0
    steps: [128, 256, 512]
    max_gen_length: [128, 256, 512]
    batch_size: 8
    remasking_strategy: ["low_confidence_dynamic"]
    target: "confidence"
    dynamic_threshold: 0.9
    block_size: 32
    further_horizon: 128
    use_cache: True
