experiment:
  project: "experiment/llada_math"
  deepspeed_file: "dp_zero3"

model:
  model_type: "llada"
  pretrained_model: "/path/to/llada-8b-instruct"

training:
  seed: 2026
  enable_tf32: True
  mixed_precision: "bf16"
  batch_size_lm: 4
  num_train_epochs: 64
  num_iterations: 1
  epsilon_low: 0.20
  epsilon_high: 0.20
  beta: 0.01
  kl_type: k3
  entropy_coeff: 0.0
  loss_norm: token
  mask_strategy: "sequential_masking"
  sample_temperature: 1
  mask_num: 4
  low_prob_threshold: 0.6
  reward_funcs: ["math"]

dataset:
  train_dataset: "MATH_rldf"
  data_type: "math"

rollout:
  batch_size: 8
  num_generations: 4
  temperature: 1.0
  steps: 256
  max_gen_length: 256
  block_size: 32
  remasking_strategy: "low_confidence_dynamic"
  target: "confidence"
  dynamic_threshold: 0.9
  use_cache: True
  further_horizon: 128

optimizer:
  name: adamw
  params:
    learning_rate: 1e-6
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
    epsilon: 1e-8

lr_scheduler:
  scheduler: "constant"
  params:
    warmup_steps: 0
    min_lr_scale: 1.0

evaluation:
  eval_dataset: "MATH500"
  data_type: "math"
  temperature: 0
  steps: 256
  max_gen_length: 256
  batch_size: 8
  block_size: 32
  remasking_strategy: "low_confidence_dynamic"
  target: "confidence"
  dynamic_threshold: 0.9
  use_cache: True
  further_horizon: 128
  eval_every_steps: 5
  eval_at_start: true
  save_after_eval: true
  top_k_checkpoints: 1
  top_k_metric: "eval_accuracy"   # Options: "eval_accuracy", "eval_reward_mean"
